# 직접 PCA를 구현한 mypca 

mypca.py 내부의 빈칸을 수정

In [1]:
import pandas as pd
import numpy as np

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn import datasets
import matplotlib.pyplot as plt

## DATA LOAD

In [2]:
iris = datasets.load_iris()
labels = np.array(iris.target).reshape(150,)
data = pd.DataFrame(iris.data,columns=['Sepal length','Sepal width','Petal length','Petal width'])

In [3]:
scaler = StandardScaler()
x = scaler.fit_transform(data)

In [4]:
x.shape

(150, 4)

### sklearn pca

In [5]:
real_pca = PCA(2)

In [6]:
real_pca_features = real_pca.fit_transform(x)

In [11]:
## 고유값 
real_pca_value =real_pca.explained_variance_
real_pca_value

array([2.93808505, 0.9201649 ])

In [9]:
## 고유벡터 
real_components = real_pca.components_
real_components

array([[ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654],
       [ 0.37741762,  0.92329566,  0.02449161,  0.06694199]])

## 만든거

In [12]:
import numpy.linalg as lin
# 공분산행렬
cov_mat = np.cov(x.T)
cov_mat.shape

(4, 4)

In [14]:
eigen_values = lin.eig(cov_mat)[0]
eigen_vectors = lin.eig(cov_mat)[1]
        

In [15]:
eigen_values

array([2.93808505, 0.9201649 , 0.14774182, 0.02085386])

In [16]:
eigen_values[:2]

array([2.93808505, 0.9201649 ])

In [17]:
eigen_vectors.T[:2,:]

array([[ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654],
       [-0.37741762, -0.92329566, -0.02449161, -0.06694199]])

In [18]:
PC1 = eigen_vectors.T[:2,:].dot(x.T).T

In [19]:
PC1

array([[-2.26470281, -0.4800266 ],
       [-2.08096115,  0.67413356],
       [-2.36422905,  0.34190802],
       [-2.29938422,  0.59739451],
       [-2.38984217, -0.64683538],
       [-2.07563095, -1.48917752],
       [-2.44402884, -0.0476442 ],
       [-2.23284716, -0.22314807],
       [-2.33464048,  1.11532768],
       [-2.18432817,  0.46901356],
       [-2.1663101 , -1.04369065],
       [-2.32613087, -0.13307834],
       [-2.2184509 ,  0.72867617],
       [-2.6331007 ,  0.96150673],
       [-2.1987406 , -1.86005711],
       [-2.26221453, -2.68628449],
       [-2.2075877 , -1.48360936],
       [-2.19034951, -0.48883832],
       [-1.898572  , -1.40501879],
       [-2.34336905, -1.12784938],
       [-1.914323  , -0.40885571],
       [-2.20701284, -0.92412143],
       [-2.7743447 , -0.45834367],
       [-1.81866953, -0.08555853],
       [-2.22716331, -0.13725446],
       [-1.95184633,  0.62561859],
       [-2.05115137, -0.24216355],
       [-2.16857717, -0.52714953],
       [-2.13956345,

### 구현한 pca

In [20]:
from mypca import mypca

%load_ext autoreload
%autoreload 2

In [21]:
my_pca = mypca(k=2)
my_pca_features = my_pca.fit_transform(x)
my_components = my_pca.components

## 결과 비교

고유벡터는 반대 방향일 수 있어서 abs의 차이로 판단

components의 결과와 data transform의 결과의 차이가 1e-6보다 작으면 정답

In [22]:
(abs(real_components)- abs(my_components)).sum() < 1e-6

True

In [23]:
real_pca_features.shape

(150, 2)

In [24]:
my_pca_features.shape

(150, 2)

In [25]:
(abs(real_pca_features)-abs(my_pca_features)).sum() < 1e-6

True