# 직접 PCA를 구현한 mypca 

mypca.py 내부의 빈칸을 수정

In [1]:
import pandas as pd
import numpy as np

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn import datasets
import matplotlib.pyplot as plt

## DATA LOAD

In [2]:
iris = datasets.load_iris()
labels = np.array(iris.target).reshape(150,)
data = pd.DataFrame(iris.data,columns=['Sepal length','Sepal width','Petal length','Petal width'])

In [3]:
scaler = StandardScaler()
x = scaler.fit_transform(data)

In [4]:
x.shape

(150, 4)

### sklearn pca

In [19]:
real_pca = PCA(4)

In [20]:
real_pca_features = real_pca.fit_transform(x)

In [21]:
## 고유값 
real_pca_value =real_pca.explained_variance_
real_pca_value

array([2.93808505, 0.9201649 , 0.14774182, 0.02085386])

In [22]:
## 고유벡터 
real_components = real_pca.components_
real_components

array([[ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654],
       [ 0.37741762,  0.92329566,  0.02449161,  0.06694199],
       [-0.71956635,  0.24438178,  0.14212637,  0.63427274],
       [-0.26128628,  0.12350962,  0.80144925, -0.52359713]])

## 만든거

In [13]:
import numpy.linalg as lin
# 공분산행렬
cov_mat = np.cov(x.T)

cov_mat.shape

(4, 4)

In [14]:
eigen_values = lin.eig(cov_mat)[0]
eigen_vectors = lin.eig(cov_mat)[1]
        

In [15]:
eigen_values

array([2.93808505, 0.9201649 , 0.14774182, 0.02085386])

In [16]:
eigen_values[:2]

array([2.93808505, 0.9201649 ])

In [23]:
eigen_vectors.T

array([[ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654],
       [-0.37741762, -0.92329566, -0.02449161, -0.06694199],
       [-0.71956635,  0.24438178,  0.14212637,  0.63427274],
       [ 0.26128628, -0.12350962, -0.80144925,  0.52359713]])

In [ ]:
PC1 = eigen_vectors.T[:2,:].dot(x.T).T

In [ ]:
PC1

### 구현한 pca

In [ ]:
from mypca import mypca

%load_ext autoreload
%autoreload 2

In [ ]:
my_pca = mypca(k=2)
my_pca_features = my_pca.fit_transform(x)
my_components = my_pca.components

## 결과 비교

고유벡터는 반대 방향일 수 있어서 abs의 차이로 판단

components의 결과와 data transform의 결과의 차이가 1e-6보다 작으면 정답

In [ ]:
(abs(real_components)- abs(my_components)).sum() < 1e-6

In [ ]:
real_pca_features.shape

In [ ]:
my_pca_features.shape

In [ ]:
(abs(real_pca_features)-abs(my_pca_features)).sum() < 1e-6